# Generated by Django 2.0.1 on 2018-03-22 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180322_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 10, 45, 35, 329553, tzinfo=utc)),
        ),
    ]
