# Generated by Django 2.0.3 on 2018-04-03 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180402_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ower',
            new_name='owner',
        ),
    ]
