# Generated by Django 2.0.3 on 2018-03-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_like',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
